## Build Stage
# Pull base image
FROM node:lts-alpine
# Install git and clone repo
RUN apk --no-cache add git
RUN git clone https://github.com/Riverbend-High-School/rhs-mesial-dashboard.git /app
# Set the working directory
WORKDIR /app
# Run dependency install
RUN npm install
# Expose web http port
EXPOSE 8080
# NGINX start command
CMD npm run serve